### ISSUE TITLE
Missing `setuptools`

### ISSUE THREAD

**Issue by compor** [opencompl/Quidditch#133]
`setuptools` is missing from the `runtime/requirements.txt` leading to a build error as it is required for building the `snitch_cluster` subproject.

Part of the output is:

```cmdline
[14/19] Performing build step for 'runtime'
[0/2] Re-checking globbed directories...
[53/141] Updating iree-compile
[0/2] Re-checking globbed directories...
ninja: no work to do.
[101/141] Generating cluster_gen/snitch_cluster_peripheral.h
FAILED: snitch_cluster/cluster_gen/snitch_cluster_peripheral.h /home/vasich/wb/build-quid2/runtime/snitch_cluster/cluster_gen/snitch_cluster_peripheral.h 
cd /home/vasich/wb/quidditch/snitch_cluster && /home/vasich/wb/quidditch/venv/bin/python3.12 /home/vasich/wb/quidditch/snitch_cluster/.bender/git/checkouts/register_interface-30a4d1663b9443bc/vendor/lowrisc_opentitan/util/regtool.py -D -o /home/vasich/wb/build-quid2/runtime/snitch_cluster/cluster_gen/snitch_cluster_peripheral.h /home/vasich/wb/quidditch/runtime/../snitch_cluster/hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson
Traceback (most recent call last):
  File "/home/vasich/wb/quidditch/snitch_cluster/.bender/git/checkouts/register_interface-30a4d1663b9443bc/vendor/lowrisc_opentitan/util/regtool.py", line 14, in <module>
    from reggen import (
  File "/home/vasich/wb/quidditch/snitch_cluster/.bender/git/checkouts/register_interface-30a4d1663b9443bc/vendor/lowrisc_opentitan/util/reggen/gen_dv.py", line 14, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
[106/141] Building C object iree-configuration/iree/runtime/src/iree/modules/hal/CMakeFiles/iree_modules_hal_hal.objects.dir/module.c.obj
ninja: build stopped: subcommand failed.
FAILED: runtime-prefix/src/runtime-stamp/runtime-build /home/vasich/wb/build-quid2/runtime-prefix/src/runtime-stamp/runtime-build 
cd /home/vasich/wb/build-quid2/runtime && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
```

**Comment by compor** [comment]
Installing `setuptools` overcomes this issue; I'll address with  a PR once all build related issues are documented.
